title: Ray's Blog
markdown: kramdown
url: "Lei-Tin.github.io"
baseurl: "/"

author:
  name: Shou-Yi (Ray), Hung
  email: xxleitinxx@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["README.md"]
